---
# Production-specific environment variables / overrides in here
deployment:

  ingress:
    hosts:
      - host: couchers.org
        paths:
          - /
      - host: prod.couchers.org
        paths:
          - /

  autoscaling:
    enabled: true

  extraEnvs:
    - name: NODE_OPTIONS
      value: "--max_old_space_size=295"

  resources:
    limits:
     cpu: 1
     memory: 300Mi
    requests:
     cpu: 100m
     memory: 300Mi

envFile: .env.production
