---
# Production-specific environment variables / overrides in here
deployment:

  ingress:
    hosts:
      - host: couchers.org
        paths:
          - /
      - host: prod.couchers.org
        paths:
          - /

  autoscaling:
    enabled: true

  extraEnvs:
    - name: NODE_OPTIONS
      value: "--max_old_space_size=500" # Testing at 50% of maximum of 2000M below

  resources:
    limits:
     cpu: 1
     memory: 1000Mi
    requests:
     cpu: 500m
     memory: 1000Mi

envFile: .env.production
