---
# Production-specific environment variables / overrides in here
deployment:

  ingress:
    hosts:
      - host: couchers.org
        paths:
          - /
      - host: prod.couchers.org
        paths:
          - /

  autoscaling:
    enabled: true

  extraEnvs:
    - name: NODE_OPTIONS
      value: "--max_old_space_size=400" # This should be 80% of maximum of 500M below

  resources:
    limits:
     cpu: 1
     memory: 500Mi
    requests:
     cpu: 500m
     memory: 500Mi

envFile: .env.production
