deployment:
  ingress:
    hosts:
      - host: staging.couchers.dev
        paths:
          - /

  # This is to "redirect" users from the old URL into the new one
  ingress_secondary:
    enabled: true
    name: app-frontend-staging-redirect
    hosts:
      - host: next.couchershq.org
        paths:
          - /
    annotations:
      nginx.ingress.kubernetes.io/permanent-redirect: https://staging.couchers.dev

  extraEnvs:
    - name: NODE_OPTIONS
      value: "--max_old_space_size=400" # This should be 80% of maximum of 200M below

  resources:
    limits:
     cpu: 500m
     memory: 500Mi
    requests:
     cpu: 50m
     memory: 500Mi

envFile: .env.staging
