deployment:
  ingress:
    hosts:
      - host: staging.couchers.dev
        paths:
          - /

  ingress_secondary:
    enabled: true
    name: app-frontend-staging-redirect
    hosts:
      - host: next.couchershq.org
        paths:
          - /
    annotations:
      nginx.ingress.kubernetes.io/permanent-redirect: https://staging.couchers.dev

  extraEnvs:
    - name: NODE_OPTIONS
      value: "--max_old_space_size=195"

  resources:
    limits:
     cpu: 500m
     memory: 200Mi
    requests:
     cpu: 50m
     memory: 200Mi

envFile: .env.staging
